POST {{host}}/v1/api/deliveries/action
Content-Type: application/json

{
  "id": "1",
  "deliveryState": "WAIT_ALLOCATE",
  "deliveryDistrict": "송파구"
}

###
POST {{host}}/v1/api/deliveries/action
Content-Type: application/json

{
  "id": "1",
  "deliveryState": "COMPLETE_ALLOCATE",
  "deliveryDistrict": "송파구"
}

###
POST {{host}}/v1/api/deliveries/action
Content-Type: application/json

{
  "id": "1",
  "deliveryState": "COMPLETE_PICKUP",
  "deliveryDistrict": "송파구"
}

###
POST {{host}}/v1/api/deliveries/action
Content-Type: application/json

{
  "id": "1",
  "deliveryState": "COMPLETE_DELIVERY",
  "deliveryDistrict": "송파구"
}

###
GET {{host}}/v1/api/deliveries/count?localDate=2022-05-02&deliveryState=COMPLETE_DELIVERY
Content-Type: application/json